### ISSUE TITLE
I found a Bug 

### ISSUE THREAD

**Issue by Flocke18** [Team-Hibiscus/NatureSpirit#100]
I found a Bug with the German name of Mahogany_ sapling.
It is writen Espenzauntor and that is wrong. 
![2024-11-23_15 46 47](https://github.com/user-attachments/assets/ec2f0df2-61fb-4317-8f22-743e3fb844c8)

**Comment by Eko-byte** [comment]
We have a crowdin page if u would be willing to put a better name https://crowdin.com/project/natures-spirit

**Comment by Flocke18** [comment]
Ja gerne und wo?
