### ISSUE TITLE
Backport Terrablender Fix compat to 1.20.1

### ISSUE THREAD

**Issue by mateus3c** [Team-Hibiscus/NatureSpirit#103]
It makes a massive difference, the world generation takes so much longer without the fix, it would be wonderful if at least this compat from version 2.0.0 was backported to 1.20.1

**Comment by Fyoncle** [comment]
Yeah i also want a backport!

**Comment by Eko-byte** [comment]
I plan on a backport for 2.0 sometime towards janruary so that will be there as well thennnn
