### ISSUE TITLE
New Ores break with Spelunkery installed

### ISSUE THREAD

**Issue by mageowl** [Team-Hibiscus/NatureSpirit#104]
With Spelunkery installed, all of the Chert ores (except for coal) have holes in place of the metals.

Minecraft 1.20.1
Nature's Spirit 1.6.3-1.20.1
Spelunkery 1.20.1-0.3.13
Quilt 0.26.4

**Comment by mageowl** [comment]
Screenshot:
![2024-11-28_08 00 53](https://github.com/user-attachments/assets/5123f660-4cd9-4999-8b4e-a2a65da0af91)

**Comment by mageowl** [comment]
In the inventory:

![image](https://github.com/user-attachments/assets/15b1b1e4-30c6-4de5-8813-f0ba81da70e9)

**Comment by Eko-byte** [comment]
Were you using the emissive ores compat resource pack? because you must also have the original emissive ores resource pack downloaded and used

**Comment by mageowl** [comment]
Yes, I didn't realize that.
