### ISSUE TITLE
[1.20.1 Fabric] Wisteria village crashing when generated and under wrong namespace

### ISSUE THREAD

**Issue by TelepathicGrunt** [Team-Hibiscus/NatureSpirit#17]
A user in the All of Fabric discord for AOF7 mentioned this crash with Wisteria Village
![IMG_0525](https://github.com/Team-Hibiscus/NatureSpirit/assets/40846040/7390099a-859e-47c5-bf5a-c20b1b984636)

There are two things to note here. 

First the crash is caused by one of the Wisteria Village’s template pool is referencing a PlacedFeature that has a biome filter check added to it. Anything with a biome filter check should only be generated by the biome. All PlacedFeatures for structures must not have the biome filter check. That’s the cause of the crash

Second issue is the village is under the minecraft namespace which is a no-no. Reason being, this Wisteria Village is not vanilla. Therefore it does not belong under minecraft namespace. It also makes it much harder for people to know who the structure is from and who to report to when there are issues. Please only use the minecraft namespace when overriding something from vanilla. If not overriding, use your own namespace

**Comment by TelepathicGrunt** [comment]
I believe this is the issue:
https://github.com/Team-Hibiscus/NatureSpirit/blob/3ab597b57aafea64b8f60c0fbd9299f52e2bb0fc/common/src/main/resources/data/minecraft/worldgen/template_pool/village/wisteria/decor.json#L15

Checking Minecraft’s json for that placedfeature, it has a biome filter placement here: 
https://github.com/misode/mcmeta/blob/5a5000efe8b642434e1687e8ed4c533fa6703695/data/minecraft/worldgen/placed_feature/forest_flowers.json#L33

Solution, make a copy of that placedfeature under your own namespace but without the biome filter placement. Then edit the template pool to point to that new placedfeature and the crash should stop.

**Comment by Eko-byte** [comment]
this shouldve been fixed last i checked let me double check

**Comment by Eko-byte** [comment]
yeah latest update fixes this
