### ISSUE TITLE
[Bug] Sandy Soil doesn't have a tool specified for faster breaking

### ISSUE THREAD

**Issue by JensenJ** [Team-Hibiscus/NatureSpirit#18]
Hi there, 
I was playing with the mod (1.20.1) and noticed that sandy soil has the same break time no matter what tool you are using, which I assume is not intended. I haven't ran across any other blocks from your mod with this issue but it may be worth double checking. Hope this helps.

Thanks for the great mod.

**Comment by ghost** [comment]
Fixed :)
