### ISSUE TITLE
terralith incompatibility

### ISSUE THREAD

**Issue by temyy** [Team-Hibiscus/NatureSpirit#22]
title, crashes when trying to generate certain biomes with both enabled. saw there was a similar issue with new world

game version 1.20.1, fabric api 0.90.7, terralith 2.4.8, natures spirit 1.2.0 (the crashlog shows 1.1.0 but ive verified its 1.2.0 installed), terrablender 3.0.0.169
[crash-2023-11-25_04.36.10-server.txt](https://github.com/Team-Hibiscus/NatureSpirit/files/13462889/crash-2023-11-25_04.36.10-server.txt)

**Comment by inikishev** [comment]
same issue

**Comment by LeoDemitori** [comment]
same issue

**Comment by Eko-byte** [comment]
fixed
