### ISSUE TITLE
[NS version 1.2.0] Paper, Framed Paper, and Blooming Paper Recipes are Missing.

### ISSUE THREAD

**Issue by adelinewesker** [Team-Hibiscus/NatureSpirit#23]
Versions:
- Fabric 1.20.1
- Fabric API 0.14.24
- Nature's Spirit Version 1.2.0.
- REI (Roughly Enough Items) version 12.0.674+fabric.

[All Paper, Framed Paper, and Blooming] Panel, Door, and Trapdoor alongside Sign and Hanging Sign Recipes seem to be missing ingredients. REI does not show the proper recipes either, and the ingredients are missing.

Attempting to craft these items (like typically how a door would be crafted) will not give an output.

Example:

![image_2023-11-25_164247156](https://github.com/Team-Hibiscus/NatureSpirit/assets/55060276/42ab90d3-98ac-46c2-9209-5d5b72b6cec1)
![image_2023-11-25_164313880](https://github.com/Team-Hibiscus/NatureSpirit/assets/55060276/e722a305-0a57-44b7-b622-e6826658e421)

**Comment by Eko-byte** [comment]
fixed
