### ISSUE TITLE
[Version 1.2.0] Rain/snow does not appear in some newly added biomes

### ISSUE THREAD

**Issue by megatrook** [Team-Hibiscus/NatureSpirit#24]
Some 1.2.0 biomes have no rain/snow at all, though they probably should.

New biomes that **don't** rain/snow: Boreal Taiga, Tundra, Heather Fields

New biomes that rain/snow normally: Tropical Shores, Coniferous Covert, Amber Covert, Alpine Clearings, Alpine Highland, Windswept Sugi Forest

I'm unsure if this is a list of every biome affected, but I hope it helps!
![image](https://github.com/Team-Hibiscus/NaturesSpirit/assets/77197776/a96588e9-0b0b-4aec-b7c5-d20d8b920570)

**Comment by Eko-byte** [comment]
this is intended for the tundra and boreal taiga, will fix for heather fields
