### ISSUE TITLE
Crashy on world load

### ISSUE THREAD

**Issue by lunekiska** [Team-Hibiscus/NatureSpirit#27]
Crash on world loading. I even added newworld compat datapack and got this
log: https://gist.githubusercontent.com/lunekiska/0e62328a3e8ab70a2b268d17d7fdff43/raw/f5c4c30e1ca5d1524694d8e6dc0a57184f8f5b42/fyes

**Comment by Anewri32** [comment]
Me too, https://mclo.gs/rbjXsmO

**Comment by lxly9** [comment]
Same here, 1.2.0 and 1.3.0

**Comment by lxly9** [comment]
https://mclo.gs/nVoVGAv https://mclo.gs/TrBihtr

**Comment by Eko-byte** [comment]
fixed

**Comment by LeoDemitori** [comment]
> fixed

1.3.0 (1.20.1) version - some crash
in which version was it fixed?

**Comment by Anewri32** [comment]
> > fixed
> 
> 1.3.0 (1.20.1) version - some crash in which version was it fixed?

From what I see, the version that fixes that bug has not yet been released.
