### ISSUE TITLE
Desert Turnips do not drop when broken, even with a Create contraption

### ISSUE THREAD

**Issue by myriantics** [Team-Hibiscus/NatureSpirit#34]
I tried harvesting them with my hand, shears, a hoe, and a create contraption and none worked :/ 

Demonstration video attached

https://github.com/Team-Hibiscus/NaturesSpirit/assets/88632676/9a526279-bd5c-4211-a5ed-7dda929a416a

**Comment by Eko-byte** [comment]
that is not how desert turnips work, they are similar to melon blocks as in u can bonemeal them to full stage and then the plant will grow a turnip 1-2 blocks beneath it after an amount of time
