### ISSUE TITLE
Game crashes when you try to Use a bucket on Half-Eaten cheese

### ISSUE THREAD

**Issue by cement-drinker** [Team-Hibiscus/NatureSpirit#39]
Exactly what the title says. If i eat the cheese and then right click it with an empty bucket, the game crashes.
I will try to put a pull request on this issue (by returning a single bucket instead of null when the bites are more than 0)

(lmfao this title is like a fever dream)

**Comment by Eko-byte** [comment]
Fixed it myself :P

**Comment by cement-drinker** [comment]
beat me to the punch :)
