### ISSUE TITLE
Crash with Blueprint 7.01 (using sinytra connector)

### ISSUE THREAD

**Issue by vivagabe** [Team-Hibiscus/NatureSpirit#45]
[crash-2024-03-01_23.55.36-client(1).txt](https://github.com/Team-Hibiscus/NaturesSpirit/files/14471866/crash-2024-03-01_23.55.36-client.1.txt)

https://www.curseforge.com/minecraft/mc-mods/blueprint
Hopefully an easy fix. Reported this to Blueprint dev as well.

**Comment by joe-vettek** [comment]
by the way, could you load the mod without blueprint

**Comment by vivagabe** [comment]
Yup. Runs fine without latest blueprint.

**Comment by Liamgrayskull** [comment]
having the same issue here

**Comment by vivagabe** [comment]
Updating to Blueprint 7.03 has resolved the issue.

**Comment by mosharky** [comment]
I have the same crash without Blueprint, not sure what could be causing it. I'm still using Connector though. Any clues?

Crash report: https://mclo.gs/ZnJUcNC
Log: https://mclo.gs/jwmBdwJ
