### ISSUE TITLE
BUG: Kaolin Bricks has the same recipe as Kaolin

### ISSUE THREAD

**Issue by s4mothy** [Team-Hibiscus/NatureSpirit#52]
This is fairly easy to temporarily fix with a datapack, but as of version 1.4.5-1.20.1, the recipe json for Kaolin Bricks uses the same recipe as Kaolin, that being 5 sand and 4 clay. Might have been an issue in previous versions, that's just the version on my server that my players brought to me. This causes the recipe for Kaolin to be unreachable without an additional mod to handle overlapping recipes, and doesn't make a ton of sense based on other brick recipes like stone-bricks. So, I'm assuming this is a bug. Altering the json should fix this.

**Comment by Eko-byte** [comment]
Thank you for bringing this up, its been fixed
