### ISSUE TITLE
Create map crash

### ISSUE THREAD

**Issue by zc1108aaa** [Team-Hibiscus/NatureSpirit#55]
[latest.log](https://github.com/Team-Hibiscus/NaturesSpirit/files/15460139/latest.log)
1
[crash-2024-05-28_03.37.19-client.txt](https://github.com/Team-Hibiscus/NaturesSpirit/files/15460138/crash-2024-05-28_03.37.19-client.txt)

**Comment by Eko-byte** [comment]
Woods and Mires is incompatible
