### ISSUE TITLE
Feature Request: Add config option to disable villages from Nature's Spirit

### ISSUE THREAD

**Issue by Routhinator** [Team-Hibiscus/NatureSpirit#63]
Hi there, thanks for the mod!

I'd like to request a config toggle to turn off the Nature's Spirit villages. I have noticed they tend to not play with other village mods. As an example I have a mod that adds names to villages, however none of the Nature's spirit villages get names. 

I'd like to turn these off as I get a lot of village diversity from other mods.

**Comment by Eko-byte** [comment]
you can go ahead and make a datapack to override the villages structure file for ur desired goals, i wont be adding this natively at least for now
