### ISSUE TITLE
1.20.1 - Optional field "music" was invalid: Failed to get element ResourceKey for 'natures_spirit:worldgen/biome/shrubby_highlands.json'

### ISSUE THREAD

**Issue by adelinewesker** [Team-Hibiscus/NatureSpirit#64]
Sorry, I'm a Sinytra Connector user 😔

Prior to adding Nature's Spirit, it was working. I'm not actually sure if it's NS doing it though, I cannot read crash logs very well.
I've downgraded NS, repaired the pack, tried both Forge and Fabric versions of Terrablender, but it didn't seem to work.

Here's the log with Cyanide - 
Log w/ Cyanide: https://pastebin.com/mXghBtQp

Here's a snippet of it:
```
Description: mouseClicked event handler

java.lang.IllegalStateException: Error(s) loading registries:


Errors(s) loading registry minecraft:worldgen/biome:

Optional field "music" was invalid: Failed to get element ResourceKey[minecraft:sound_event / minecraft:music.overworld.arid]
	at: "effects"
	at: worldgen/biome 'natures_spirit:worldgen/biome/shrubby_highlands.json'
	at: pack 'naturespirit-1.5.3-1.20.1_mapped_srg_1.20.1.jar'
```

**Comment by Eko-byte** [comment]
Fixed
