### ISSUE TITLE
naturespirit-1.0-1.20.1.jar not working on server?

### ISSUE THREAD

**Issue by SHXRKIIE** [Team-Hibiscus/NatureSpirit#7]
Hi so I am testing your mod on a server and it runs but some reason you cant locate the biome or structures with /locate but it does work in singleplayer

**Comment by Eletoast** [comment]
Fairly sure they're working on a fix right now. Shouldn't be too long until its resolved.

**Comment by Trent2087** [comment]
This is fixed in dev. I just built the source to test it. Hopefully there will be a new release soon

**Comment by Eko-byte** [comment]
omg i forget to check the issues guys super sorry, its been fixed as of now i had some server issues I think
