### ISSUE TITLE
1.21 Crash on start \\ Access Widener Error

### ISSUE THREAD

**Issue by makumaku1974** [Team-Hibiscus/NatureSpirit#70]
![Screenshot 2024-07-04 092058](https://github.com/Team-Hibiscus/NaturesSpirit/assets/129804277/cb3a23b6-620a-4b9a-8094-f83633f2aa0d)

https://mclo.gs/PxagSu9

**Comment by Eko-byte** [comment]
Likely a fabric loader version error, fabric api version error, or incompat with one of your 200 mods loadedd

**Comment by makumaku1974** [comment]
is there a part where I should change my fabric loader or api version?

That would likely be a lot to do in finding the right versions.
