### ISSUE TITLE
Upon creating a new world, I automatically get "adventuring time" achievement (1.21 fabric)

### ISSUE THREAD

**Issue by cobaltlol2** [Team-Hibiscus/NatureSpirit#71]
It's self-explanatory really, I do wanna add that removing nature's spirit seems to fix it so I don't see which other mod could cause this

**Comment by wh0isit** [comment]
Can confirm this on versions 1.5.4 & 1.5.5. Does not happen with 1.5.3.

**Comment by Eko-byte** [comment]
Fixed for next version
