### ISSUE TITLE
Missing textures?

### ISSUE THREAD

**Issue by LumineMochi** [Team-Hibiscus/NatureSpirit#72]
![Screenshot 2024-07-13 104358](https://github.com/user-attachments/assets/3115841c-d652-4a7c-a939-d914f1ce99ea)

I'm not fully sure how to address what's wrong besides me saying that the leaves texture isn't working anymore. All the trees turn to the block that's pink and black as based on the pic. It was fine the first time around and I thought I just need to reinstall the mod. After that it would work but then the next day or when I close the game and open it again later, it would be back to the pink and black block. I'm not sure what's wrong and I would like help

**Comment by LumineMochi** [comment]
I joined the discord and found the solution ^^

**Comment by fenrave** [comment]
To spare future people who find this closed issue, the problem is the bushy leaves resource pack
