### ISSUE TITLE
[Bug] Items have forge tags in the fabric version

### ISSUE THREAD

**Issue by masuteri** [Team-Hibiscus/NatureSpirit#76]
For example stripped logs show up like this:
![kuva](https://github.com/user-attachments/assets/eebbd704-ddaa-421f-bffc-dc3c9f94a02b)

instead of showing up like they should here
![kuva](https://github.com/user-attachments/assets/2cbdc8fd-d6d5-4871-aedd-dd8cb976f4d4)

**Comment by Eko-byte** [comment]
This was done for sinytra compatibility with forge create, will be adding more things to common tag tho
