### ISSUE TITLE
1.6.1-1.20.1 and above crash with Create, Farmer's Delight, and compatibility addons

### ISSUE THREAD

**Issue by Angelic-Aether** [Team-Hibiscus/NatureSpirit#80]
What the title says.

Crash report:
[crash-2024-08-19_16.56.01-client.txt](https://github.com/user-attachments/files/16656796/crash-2024-08-19_16.56.01-client.txt)

I also have [Nature's Delight](https://modrinth.com/mod/natures-delight) and [Nature's Spirit - Create Recipe Compat](https://modrinth.com/datapack/ns-cr-rc) installed.

Full mod list in case any of my other mods are causing the crash: https://modrinth.com/modpack/diamond-dimensions-reborn

**Comment by uczpre** [comment]
be more specific sweetie , i believe your experiencing the same issue as me.
