### ISSUE TITLE
[Bug] adobe village houses pool missing

### ISSUE THREAD

**Issue by xXNickznXx** [Team-Hibiscus/NatureSpirit#89]
On `naturespirit-1.6.2-1.21`

Im trying to add custom structures to the villages of this mod utilizing the [Structure Pool API](https://modrinth.com/mod/structure-pool-api) mod.

For the coconut, cypress and wisteria villages it works fine, but for the adobe village is seems the pool is missing.

Using the `natures_spirit:village/<village_name>/houses` pools

**Comment by Eko-byte** [comment]
Yeah because Adobe villages are differently structured and also use multiple pools to maximize randomness. If you would, we can connect on discord and I can try helping u figure out how to implement your stuff for the adobe villages

**Comment by xXNickznXx** [comment]
@Eko-byte i have managed it on my own. There were a couple of things i have done wrong:

1. I was trying to add to a nonexistent pool: `natures_spirit:village/adobe/houses` instead of adding to one that exists: `natures_spirit:village/adobe/adobe_houses_layer_1`
2. I was using the wrong (default for "normal" villages) configuration in the jigsaw blocks instead of using your configurations
